/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_CommunityProperty')
	begin
		print 'Dropping Procedure ManagedFusion_CommunityProperty'
		drop procedure ManagedFusion_CommunityProperty
	end
go

print 'Creating Procedure ManagedFusion_CommunityProperty'
go

create procedure ManagedFusion_CommunityProperty
(
	@CommunityID as int = null,
	@PropertyGroup as nvarchar(32) = null,
	@Name as nvarchar(32) = null,
	@Value as ntext
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into CommunityProperty.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [CommunityProperty] 
	where 
		[CommunityID] = @CommunityID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name
) begin

	update 
		[CommunityProperty]
	
	set
		[CommunityID] = @CommunityID,
		[PropertyGroup] = @PropertyGroup,
		[Name] = @Name,
		[Value] = @Value
	
	where
		[CommunityID] = @CommunityID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name

end else begin

	insert into [CommunityProperty] (
		[CommunityID],
		[PropertyGroup],
		[Name],
		[Value]
	) values (
		@CommunityID,
		@PropertyGroup,
		@Name,
		@Value
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_CommunityProperty_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_CommunityProperty_Delete'
		drop procedure ManagedFusion_CommunityProperty_Delete
	end
go

print 'Creating Procedure ManagedFusion_CommunityProperty_Delete'
go

create procedure ManagedFusion_CommunityProperty_Delete
(
	@CommunityID as int,
	@PropertyGroup as nvarchar(32),
	@Name as nvarchar(32)
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in CommunityProperty.

delete from 
	[CommunityProperty]

where
	[CommunityID] = @CommunityID
	and [PropertyGroup] = @PropertyGroup
	and [Name] = @Name

go

set nocount off