/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Container')
	begin
		print 'Dropping Procedure ManagedFusion_Container'
		drop procedure ManagedFusion_Container
	end
go

print 'Creating Procedure ManagedFusion_Container'
go

create procedure ManagedFusion_Container
(
	@ContainerID as int = null,
	@Name as nvarchar(32),
	@Description as nvarchar(128),
	@Touched as datetime
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into Container.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [Container] 
	where 
		[ContainerID] = @ContainerID
) begin

	update 
		[Container]
	
	set
		[Name] = @Name,
		[Description] = @Description,
		[Touched] = @Touched
	
	where
		[ContainerID] = @ContainerID

end else begin

	insert into [Container] (
		[ContainerID],
		[Name],
		[Description],
		[Touched]
	) values (
		@ContainerID,
		@Name,
		@Description,
		@Touched
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Container_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_Container_Delete'
		drop procedure ManagedFusion_Container_Delete
	end
go

print 'Creating Procedure ManagedFusion_Container_Delete'
go

create procedure ManagedFusion_Container_Delete
(
	@ContainerID as int
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in Container.

delete from 
	[Container]

where
	[ContainerID] = @ContainerID

go

set nocount off