/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Portlet')
	begin
		print 'Dropping Procedure ManagedFusion_Portlet'
		drop procedure ManagedFusion_Portlet
	end
go

print 'Creating Procedure ManagedFusion_Portlet'
go

create procedure ManagedFusion_Portlet
(
	@PortletID as int = null,
	@Name as nvarchar(32),
	@Description as nvarchar(128),
	@Touched as datetime,
	@ModuleID as uniqueidentifier
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into Portlet.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [Portlet] 
	where 
		[PortletID] = @PortletID
) begin

	update 
		[Portlet]
	
	set
		[Name] = @Name,
		[Description] = @Description,
		[Touched] = @Touched,
		[ModuleID] = @ModuleID
	
	where
		[PortletID] = @PortletID

end else begin

	insert into [Portlet] (
		[PortletID],
		[Name],
		[Description],
		[Touched],
		[ModuleID]
	) values (
		@PortletID,
		@Name,
		@Description,
		@Touched,
		@ModuleID
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Portlet_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_Portlet_Delete'
		drop procedure ManagedFusion_Portlet_Delete
	end
go

print 'Creating Procedure ManagedFusion_Portlet_Delete'
go

create procedure ManagedFusion_Portlet_Delete
(
	@PortletID as int
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in Portlet.

delete from 
	[Portlet]

where
	[PortletID] = @PortletID

go

set nocount off