/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_PortletProperty')
	begin
		print 'Dropping Procedure ManagedFusion_PortletProperty'
		drop procedure ManagedFusion_PortletProperty
	end
go

print 'Creating Procedure ManagedFusion_PortletProperty'
go

create procedure ManagedFusion_PortletProperty
(
	@PortletID as int = null,
	@PropertyGroup as nvarchar(32) = null,
	@Name as nvarchar(32) = null,
	@Value as ntext
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into PortletProperty.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [PortletProperty] 
	where 
		[PortletID] = @PortletID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name
) begin

	update 
		[PortletProperty]
	
	set
		[PortletID] = @PortletID,
		[PropertyGroup] = @PropertyGroup,
		[Name] = @Name,
		[Value] = @Value
	
	where
		[PortletID] = @PortletID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name

end else begin

	insert into [PortletProperty] (
		[PortletID],
		[PropertyGroup],
		[Name],
		[Value]
	) values (
		@PortletID,
		@PropertyGroup,
		@Name,
		@Value
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_PortletProperty_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_PortletProperty_Delete'
		drop procedure ManagedFusion_PortletProperty_Delete
	end
go

print 'Creating Procedure ManagedFusion_PortletProperty_Delete'
go

create procedure ManagedFusion_PortletProperty_Delete
(
	@PortletID as int,
	@PropertyGroup as nvarchar(32),
	@Name as nvarchar(32)
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in PortletProperty.

delete from 
	[PortletProperty]

where
	[PortletID] = @PortletID
	and [PropertyGroup] = @PropertyGroup
	and [Name] = @Name

go

set nocount off