/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_SectionProperty')
	begin
		print 'Dropping Procedure ManagedFusion_SectionProperty'
		drop procedure ManagedFusion_SectionProperty
	end
go

print 'Creating Procedure ManagedFusion_SectionProperty'
go

create procedure ManagedFusion_SectionProperty
(
	@SectionID as int = null,
	@PropertyGroup as nvarchar(32) = null,
	@Name as nvarchar(32) = null,
	@Value as ntext
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into SectionProperty.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [SectionProperty] 
	where 
		[SectionID] = @SectionID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name
) begin

	update 
		[SectionProperty]
	
	set
		[SectionID] = @SectionID,
		[PropertyGroup] = @PropertyGroup,
		[Name] = @Name,
		[Value] = @Value
	
	where
		[SectionID] = @SectionID
		and [PropertyGroup] = @PropertyGroup
		and [Name] = @Name

end else begin

	insert into [SectionProperty] (
		[SectionID],
		[PropertyGroup],
		[Name],
		[Value]
	) values (
		@SectionID,
		@PropertyGroup,
		@Name,
		@Value
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_SectionProperty_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_SectionProperty_Delete'
		drop procedure ManagedFusion_SectionProperty_Delete
	end
go

print 'Creating Procedure ManagedFusion_SectionProperty_Delete'
go

create procedure ManagedFusion_SectionProperty_Delete
(
	@SectionID as int,
	@PropertyGroup as nvarchar(32),
	@Name as nvarchar(32)
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in SectionProperty.

delete from 
	[SectionProperty]

where
	[SectionID] = @SectionID
	and [PropertyGroup] = @PropertyGroup
	and [Name] = @Name

go

set nocount off