/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_SectionContainerLink')
	begin
		print 'Dropping Procedure ManagedFusion_SectionContainerLink'
		drop procedure ManagedFusion_SectionContainerLink
	end
go

print 'Creating Procedure ManagedFusion_SectionContainerLink'
go

create procedure ManagedFusion_SectionContainerLink
(
	@SectionID as int = null,
	@ContainerID as int = null,
	@SortOrder as int,
	@Position as int
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into SectionContainerLink.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [SectionContainerLink] 
	where 
		[SectionID] = @SectionID
		and [ContainerID] = @ContainerID
) begin

	update 
		[SectionContainerLink]
	
	set
		[SectionID] = @SectionID,
		[ContainerID] = @ContainerID,
		[SortOrder] = @SortOrder,
		[Position] = @Position
	
	where
		[SectionID] = @SectionID
		and [ContainerID] = @ContainerID

end else begin

	insert into [SectionContainerLink] (
		[SectionID],
		[ContainerID],
		[SortOrder],
		[Position]
	) values (
		@SectionID,
		@ContainerID,
		@SortOrder,
		@Position
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_SectionContainerLink_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_SectionContainerLink_Delete'
		drop procedure ManagedFusion_SectionContainerLink_Delete
	end
go

print 'Creating Procedure ManagedFusion_SectionContainerLink_Delete'
go

create procedure ManagedFusion_SectionContainerLink_Delete
(
	@SectionID as int,
	@ContainerID as int
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in SectionContainerLink.

delete from 
	[SectionContainerLink]

where
	[SectionID] = @SectionID
	and [ContainerID] = @ContainerID

go

set nocount off