/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Site')
	begin
		print 'Dropping Procedure ManagedFusion_Site'
		drop procedure ManagedFusion_Site
	end
go

print 'Creating Procedure ManagedFusion_Site'
go

create procedure ManagedFusion_Site
(
	@SiteID as int = null,
	@SectionID as int,
	@Name as nvarchar(32),
	@Description as nvarchar(128),
	@Touched as datetime,
	@SubDomain as nvarchar(128),
	@Domain as nvarchar(128),
	@Theme as nvarchar(64),
	@Style as nvarchar(64)
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Inserts or updates an entity into Site.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [Site] 
	where 
		[SiteID] = @SiteID
) begin

	update 
		[Site]
	
	set
		[SectionID] = @SectionID,
		[Name] = @Name,
		[Description] = @Description,
		[Touched] = @Touched,
		[SubDomain] = @SubDomain,
		[Domain] = @Domain,
		[Theme] = @Theme,
		[Style] = @Style
	
	where
		[SiteID] = @SiteID

end else begin

	insert into [Site] (
		[SiteID],
		[SectionID],
		[Name],
		[Description],
		[Touched],
		[SubDomain],
		[Domain],
		[Theme],
		[Style]
	) values (
		@SiteID,
		@SectionID,
		@Name,
		@Description,
		@Touched,
		@SubDomain,
		@Domain,
		@Theme,
		@Style
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'ManagedFusion_Site_Delete')
	begin
		print 'Dropping Procedure ManagedFusion_Site_Delete'
		drop procedure ManagedFusion_Site_Delete
	end
go

print 'Creating Procedure ManagedFusion_Site_Delete'
go

create procedure ManagedFusion_Site_Delete
(
	@SiteID as int
)
as

--	Author:		ManagedFusion [http://www.managedfusion.com]
--	Date:		11/22/2006
--	Purpose:	Delete the entity in Site.

delete from 
	[Site]

where
	[SiteID] = @SiteID

go

set nocount off