/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Security.Permissions;
using System.Xml;
using System.Xml.Serialization;

namespace ManagedFusion.Data.SqlServer2000
{
	[DataObject(true)]
	public partial class ContainerPortletLink : ITable<int>
	{
		#region Static Methods
		
		#region Common Methods

		protected static ContainerPortletLinkCollection FillCollection (SqlCommand command)
		{
			ContainerPortletLinkCollection list = new ContainerPortletLinkCollection();
			
			try
			{
				command.Connection.Open();
				using(SqlDataReader reader = command.ExecuteReader())
				{
					if (reader.HasRows)
					{
						int[] order = new int[3];
						order[0] = reader.GetOrdinal("ContainerID");
						order[1] = reader.GetOrdinal("PortletID");
						order[2] = reader.GetOrdinal("SortOrder");

						while (reader.Read()) 
						{
							ContainerPortletLink entity = new ContainerPortletLink();
							entity._containerID = reader.IsDBNull(0) ? 0 :  reader.GetInt32(order[0]); // ContainerID
							entity._portletID = reader.IsDBNull(1) ? 0 :  reader.GetInt32(order[1]); // PortletID
							entity._sortOrder = reader.IsDBNull(2) ? 0 :  reader.GetInt32(order[2]); // SortOrder

							// add to list
							list.Add(entity);
						}
					}
				}
			} catch (Exception exc) {
				Debug.WriteLine(exc);
			} finally {
				command.Connection.Close();
			}
					
			return list;
		}
	
		protected static ContainerPortletLink FillEntity (SqlCommand command)
		{
			ContainerPortletLink entity = null;
			
			try
			{
				command.Connection.Open();
				using(SqlDataReader reader = command.ExecuteReader())
				{
					if (reader.HasRows)
					{
						reader.Read();
						entity = new ContainerPortletLink();
						entity._containerID = reader.IsDBNull(0) ? 0 :  reader.GetInt32(reader.GetOrdinal("ContainerID"));
						entity._portletID = reader.IsDBNull(1) ? 0 :  reader.GetInt32(reader.GetOrdinal("PortletID"));
						entity._sortOrder = reader.IsDBNull(2) ? 0 :  reader.GetInt32(reader.GetOrdinal("SortOrder"));
					}
				}
			} catch (Exception exc) {
				Debug.WriteLine(exc);
			} finally {
				if (entity == null) 
					entity = new ContainerPortletLink();
					
				command.Connection.Close();
			}
					
			return entity;
		}
		
		#endregion
		
		#region Get List
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLinkCollection GetList (string where, string orderBy)
		{
			StringBuilder sb = new StringBuilder(10);
			
			sb.Append(@"select * from [ContainerPortletLink] ");
			
			if (String.IsNullOrEmpty(where) == false)
			{
				sb.Append(" where ");
				sb.Append("(");
				sb.Append(where);
				sb.Append(")");
			}
			
			if (String.IsNullOrEmpty(orderBy) == false)
			{
				sb.Append(" order by ");
				sb.Append(orderBy);
			}
			
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = sb.ToString();
					command.CommandType = CommandType.Text;
					
					return FillCollection(command);
				}
			}
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLinkCollection GetList (string where)
		{
			return GetList(where, String.Empty);
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, true)]
		public static ContainerPortletLinkCollection GetList ()
		{
			return GetList(String.Empty, String.Empty);
		}
		
		#endregion
		
		#region Get First
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetFirst (string where, string orderBy)
		{
			StringBuilder sb = new StringBuilder(10);
			
			sb.Append(@"select top 1 * from [ContainerPortletLink] ");
			
			if (String.IsNullOrEmpty(where) == false)
			{
				sb.Append(" where ");
				sb.Append("(");
				sb.Append(where);
				sb.Append(")");
			}
			
			if (String.IsNullOrEmpty(orderBy) == false)
			{
				sb.Append(" order by ");
				sb.Append(orderBy);
			}
			
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = sb.ToString();
					command.CommandType = CommandType.Text;
					
					return FillEntity(command);
				}
			}
		}
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetFirst (string where)
		{
			return GetFirst(where, String.Empty);
		}
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetFirst ()
		{
			return GetFirst(String.Empty, String.Empty);
		}
		
		#endregion
		
		#region Get Latest
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetLatest (string where)
		{
			return GetFirst(where, "ModifiedDT desc");
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetLatest ()
		{
			return GetLatest(String.Empty);
		}
		
		#endregion
		
		#region Get By Foreign Key
		
		#endregion
		
		#region Get By Index
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetByContainerIDAndPortletID(int containerID, int portletID, string orderBy)
		{
			return GetFirst("ContainerID = " + containerID + " and PortletID = " + portletID + "", orderBy);
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static ContainerPortletLink GetByContainerIDAndPortletID(int containerID, int portletID)
		{
			return GetByContainerIDAndPortletID(containerID, portletID, String.Empty);
		}
		
		#endregion

		#region Insert
		
		protected static bool InsertOrUpdate (int containerID, int portletID, int sortOrder)		
		{
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = "ManagedFusion_ContainerPortletLink";
					command.CommandType = CommandType.StoredProcedure;
					
					command.Parameters.AddWithValue("@ContainerID", containerID);
					command.Parameters.AddWithValue("@PortletID", portletID);
					command.Parameters.AddWithValue("@SortOrder", sortOrder);
					
					bool success = false;
					
					try
					{
						connection.Open();
						command.ExecuteNonQuery();
					
						success = true;
					} catch (Exception exc) {
						Debug.WriteLine(exc);
						
						success = false;
					} finally {
						connection.Close();
					}
					
					return success;
				}
			}
		}
		
		[DataObjectMethod(DataObjectMethodType.Insert, false)]
		public static bool Insert (int containerID, int portletID, int sortOrder)
		{
			return InsertOrUpdate(
				containerID,
				portletID,
				sortOrder
			);
		}
		
		[DataObjectMethod(DataObjectMethodType.Insert, true)]
		public static bool Insert (ContainerPortletLink entity)
		{
			entity.AcceptChanges();
			return InsertOrUpdate(
				entity.ContainerID, 
				entity.PortletID, 
				entity.SortOrder
			);
		}
		
		#endregion
		
		#region Update
		
		[DataObjectMethod(DataObjectMethodType.Update, false)]
		public static bool Update (int containerID, int portletID, int sortOrder)
		{
			return InsertOrUpdate(
				containerID,
				portletID,
				sortOrder
			);
		}
		
		[DataObjectMethod(DataObjectMethodType.Update, true)]
		public static bool Update (ContainerPortletLink entity)
		{
			entity.AcceptChanges();
			return InsertOrUpdate(
				entity.ContainerID, 
				entity.PortletID, 
				entity.SortOrder
				);
		}
		
		#endregion
		
		#region Delete
		
		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static bool Delete (ContainerPortletLink entity)
		{
			entity.AcceptChanges();
			return Delete(
				entity.ContainerID, 
				entity.PortletID
			);
		}

		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static bool Delete (int containerID, int portletID)
		{
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = "ManagedFusion_ContainerPortletLink_Delete";
					command.CommandType = CommandType.StoredProcedure;
					
					command.Parameters.AddWithValue("@ContainerID", containerID);
					command.Parameters.AddWithValue("@PortletID", portletID);
					
					bool success = false;
					
					try
					{
						connection.Open();
						command.ExecuteNonQuery();
					
						success = true;
					} catch (Exception exc) {
						Debug.WriteLine(exc);
						
						success = false;
					} finally {
						connection.Close();
					}
					
					return success;
				}
			}
		}
		
		#endregion

		#endregion
		
		#region Column Variables
		
		#region Primary key(s)
		
		/// <summary>			
		/// Column ContainerID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ContainerPortletLink"</remarks>
		private int _containerID = 0;

		/// <summary>			
		/// Column PortletID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ContainerPortletLink"</remarks>
		private int _portletID = 0;

		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// Column SortOrder : 
		/// </summary>
		private int _sortOrder = 0;

		#endregion
		
		#endregion
		
		#region Constructor
		
		///<summary>
		/// Creates a new <see cref="ContainerPortletLink"/> instance.
		///</summary>
		///<param name="ContainerID"></param>
		///<param name="PortletID"></param>
		///<param name="SortOrder"></param>
		public ContainerPortletLink (int containerID, int portletID, int sortOrder)
		{
			this._isMarkedForDeletion = false;
			this._isDirty = true;
			this._isNew = true;
			this._autoUpdate = true;
				
			this._containerID = containerID;
			this._portletID = portletID;
			this._sortOrder = sortOrder;
		}
		
		public ContainerPortletLink ()
		{
			this._isMarkedForDeletion = false;
			this._isDirty = false;
			this._isNew = true;
			this._autoUpdate = true;
		}
		
		#endregion
		
		#region Properties
		
		#region Foreign Keys
		
		#endregion
		
		/// <summary>Gets the ContainerID value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is int</value>
		[ReadOnly(true)]
		[Description("")]
		[DataObjectField(true, false, false, 4)]
		public int ContainerID
		{
			get { return this._containerID; }
		}
		
		/// <summary>Gets the PortletID value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is int</value>
		[ReadOnly(true)]
		[Description("")]
		[DataObjectField(true, false, false, 4)]
		public int PortletID
		{
			get { return this._portletID; }
		}
		
		/// <summary>Gets or sets the SortOrder value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is int</value>
		[Description("")]
		[DataObjectField(false, false, false, 4)]
		public int SortOrder
		{
			get { return this._sortOrder; }
			set
			{
				if (_sortOrder == value)
					return;
					
				_sortOrder = value;
				this._isDirty = true;
				
				// if auto update is turned on update this
				if (AllowAutoUpdate) Update(this);
			}
		}
		

		private bool _autoUpdate = true;
		/// <summary>True if the entity should commit changes as soon as they are made.</summary>
		[Browsable(false)]
		public bool AutoUpdate
		{
			get { return this._autoUpdate; }
			set { _autoUpdate = value; }
		}

		private bool _isMarkedForDeletion = false;
		/// <summary>Gets if the object has been <see cref="MarkToDelete"/>.</summary>
		[Browsable(false)]
		public bool IsMarkedForDeletion
		{
			get { return this._isMarkedForDeletion; }
		}

		private bool _isDirty = false;
		/// <summary>Indicates if the object has been modified from its original state.</summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[Browsable(false)]
		public bool IsDirty
		{
			get { return this._isDirty; }
		}

		private bool _isNew = false;
		/// <summary>Indicates if the object is new.</summary>
		///<value>True if objectis new; otherwise False;</value>
		[Browsable(false)]
		public bool IsNew
		{
			get { return this._isNew; }
		}

		/// <summary>Gets a value indicating if AutoUpdate is allowed on this entity.</summary>
		private bool AllowAutoUpdate 
		{
			get { return (!IsNew && !IsMarkedForDeletion) && AutoUpdate; }
		}

		#endregion
		
		#region Methods
		
		internal void Merge (ContainerPortletLink entity)
		{
			this._containerID = entity._containerID;
			this._portletID = entity._portletID;
			this._sortOrder = entity._sortOrder;
		}

		/// <summary>Begin the update process.</summary>
		public void BeginUpdate()
		{
			this.AutoUpdate = false;
		}
		
		/// <summary>End the update process and commit changes.</summary>
		public void EndUpdate()
		{
			this.EndUpdate(true);
		}
		
		/// <summary>End the update process</summary>
		public void EndUpdate(bool commit)
		{
			this.AutoUpdate = true;
			
			if (commit)
				this.CommitChanges();
		}
		
		/// <summary>Accepts the changes made to this object by setting each flags to false.</summary>
		internal void AcceptChanges()
		{
			this._isMarkedForDeletion = false;
			this._isDirty = false;
			this._isNew = false;
		}
		
		///<summary>Currently not supported.</summary>
		public void CancelChanges()
		{
			throw new NotSupportedException("Cancel changes is not currently supported.");
		}
		
		///<summary>Delete this entity.</summary>
		public void Delete()
		{
			this._isMarkedForDeletion = true;
			
			if (!IsNew && AutoUpdate) Delete(this);
		}
		
		#endregion
		
		#region ITable<int> Members

		[DataObjectField(true, true, false)]
		int ITable<int>.PrimaryKey
		{
			get { return _containerID; }
		}

		/// <summary>Commit the changes to the database.</summary>
		public void CommitChanges()
		{
			if (this.IsNew)
				Insert(this);
			
			else if (this.IsMarkedForDeletion)
				Delete(this);
				
			else if (this.IsDirty)
				Update(this);
		}

		#endregion
	}
	
	#region ContainerPortletLink Columns
	
	public enum ContainerPortletLinkColumn
	{
		/// <summary></summary>
		ContainerID,
 
		/// <summary></summary>
		PortletID,
 
		/// <summary></summary>
		SortOrder 
	}
	
	#endregion
	
	#region ContainerPortletLink Collection
	
	public class ContainerPortletLinkCollection : TableCollection<int, ContainerPortletLink>
	{
	}
	
	#endregion
}