/*
 * 	Template:		This code was generated by the ManagedFusion [http://www.managedfusion.com] Data Layer Template.
 * 	Created On :	11/22/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Security.Permissions;
using System.Xml;
using System.Xml.Serialization;

namespace ManagedFusion.Data.SqlServer2000
{
	[DataObject(true)]
	public partial class Portlet : ITable<int>
	{
		#region Static Methods
		
		#region Common Methods

		protected static PortletCollection FillCollection (SqlCommand command)
		{
			PortletCollection list = new PortletCollection();
			
			try
			{
				command.Connection.Open();
				using(SqlDataReader reader = command.ExecuteReader())
				{
					if (reader.HasRows)
					{
						int[] order = new int[5];
						order[0] = reader.GetOrdinal("PortletID");
						order[1] = reader.GetOrdinal("Name");
						order[2] = reader.GetOrdinal("Description");
						order[3] = reader.GetOrdinal("Touched");
						order[4] = reader.GetOrdinal("ModuleID");

						while (reader.Read()) 
						{
							Portlet entity = new Portlet();
							entity._portletID = reader.IsDBNull(0) ? 0 :  reader.GetInt32(order[0]); // PortletID
							entity._name = reader.IsDBNull(1) ? String.Empty :  reader.GetString(order[1]); // Name
							entity._description = reader.IsDBNull(2) ? (string)null :  reader.GetString(order[2]); // Description
							entity._touched = reader.IsDBNull(3) ? (DateTime)SqlDateTime.MinValue :  reader.GetDateTime(order[3]); // Touched
							entity._moduleID = reader.IsDBNull(4) ? Guid.Empty :  reader.GetGuid(order[4]); // ModuleID

							// add to list
							list.Add(entity);
						}
					}
				}
			} catch (Exception exc) {
				Debug.WriteLine(exc);
			} finally {
				command.Connection.Close();
			}
					
			return list;
		}
	
		protected static Portlet FillEntity (SqlCommand command)
		{
			Portlet entity = null;
			
			try
			{
				command.Connection.Open();
				using(SqlDataReader reader = command.ExecuteReader())
				{
					if (reader.HasRows)
					{
						reader.Read();
						entity = new Portlet();
						entity._portletID = reader.IsDBNull(0) ? 0 :  reader.GetInt32(reader.GetOrdinal("PortletID"));
						entity._name = reader.IsDBNull(1) ? String.Empty :  reader.GetString(reader.GetOrdinal("Name"));
						entity._description = reader.IsDBNull(2) ? (string)null :  reader.GetString(reader.GetOrdinal("Description"));
						entity._touched = reader.IsDBNull(3) ? (DateTime)SqlDateTime.MinValue :  reader.GetDateTime(reader.GetOrdinal("Touched"));
						entity._moduleID = reader.IsDBNull(4) ? Guid.Empty :  reader.GetGuid(reader.GetOrdinal("ModuleID"));
					}
				}
			} catch (Exception exc) {
				Debug.WriteLine(exc);
			} finally {
				if (entity == null) 
					entity = new Portlet();
					
				command.Connection.Close();
			}
					
			return entity;
		}
		
		#endregion
		
		#region Get List
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static PortletCollection GetList (string where, string orderBy)
		{
			StringBuilder sb = new StringBuilder(10);
			
			sb.Append(@"select * from [Portlet] ");
			
			if (String.IsNullOrEmpty(where) == false)
			{
				sb.Append(" where ");
				sb.Append("(");
				sb.Append(where);
				sb.Append(")");
			}
			
			if (String.IsNullOrEmpty(orderBy) == false)
			{
				sb.Append(" order by ");
				sb.Append(orderBy);
			}
			
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = sb.ToString();
					command.CommandType = CommandType.Text;
					
					return FillCollection(command);
				}
			}
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static PortletCollection GetList (string where)
		{
			return GetList(where, String.Empty);
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, true)]
		public static PortletCollection GetList ()
		{
			return GetList(String.Empty, String.Empty);
		}
		
		#endregion
		
		#region Get First
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetFirst (string where, string orderBy)
		{
			StringBuilder sb = new StringBuilder(10);
			
			sb.Append(@"select top 1 * from [Portlet] ");
			
			if (String.IsNullOrEmpty(where) == false)
			{
				sb.Append(" where ");
				sb.Append("(");
				sb.Append(where);
				sb.Append(")");
			}
			
			if (String.IsNullOrEmpty(orderBy) == false)
			{
				sb.Append(" order by ");
				sb.Append(orderBy);
			}
			
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = sb.ToString();
					command.CommandType = CommandType.Text;
					
					return FillEntity(command);
				}
			}
		}
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetFirst (string where)
		{
			return GetFirst(where, String.Empty);
		}
	
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetFirst ()
		{
			return GetFirst(String.Empty, String.Empty);
		}
		
		#endregion
		
		#region Get Latest
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetLatest (string where)
		{
			return GetFirst(where, "ModifiedDT desc");
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetLatest ()
		{
			return GetLatest(String.Empty);
		}
		
		#endregion
		
		#region Get By Foreign Key
		
		#endregion
		
		#region Get By Index
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetByPortletID(int portletID, string orderBy)
		{
			return GetFirst("PortletID = " + portletID + "", orderBy);
		}
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
		public static Portlet GetByPortletID(int portletID)
		{
			return GetByPortletID(portletID, String.Empty);
		}
		
		#endregion

		#region Insert
		
		protected static bool InsertOrUpdate (int portletID, string name, string description, DateTime touched, Guid moduleID)		
		{
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = "ManagedFusion_Portlet";
					command.CommandType = CommandType.StoredProcedure;
					
					command.Parameters.AddWithValue("@PortletID", portletID);
					command.Parameters.AddWithValue("@Name", name);
					command.Parameters.AddWithValue("@Description", description);
					command.Parameters.AddWithValue("@Touched", touched);
					command.Parameters.AddWithValue("@ModuleID", moduleID);
					
					bool success = false;
					
					try
					{
						connection.Open();
						command.ExecuteNonQuery();
					
						success = true;
					} catch (Exception exc) {
						Debug.WriteLine(exc);
						
						success = false;
					} finally {
						connection.Close();
					}
					
					return success;
				}
			}
		}
		
		[DataObjectMethod(DataObjectMethodType.Insert, false)]
		public static bool Insert (int portletID, string name, string description, DateTime touched, Guid moduleID)
		{
			return InsertOrUpdate(
				portletID,
				name,
				description,
				touched,
				moduleID
			);
		}
		
		[DataObjectMethod(DataObjectMethodType.Insert, true)]
		public static bool Insert (Portlet entity)
		{
			entity.AcceptChanges();
			return InsertOrUpdate(
				entity.PortletID, 
				entity.Name, 
				entity.Description, 
				entity.Touched, 
				entity.ModuleID
			);
		}
		
		#endregion
		
		#region Update
		
		[DataObjectMethod(DataObjectMethodType.Update, false)]
		public static bool Update (int portletID, string name, string description, DateTime touched, Guid moduleID)
		{
			return InsertOrUpdate(
				portletID,
				name,
				description,
				touched,
				moduleID
			);
		}
		
		[DataObjectMethod(DataObjectMethodType.Update, true)]
		public static bool Update (Portlet entity)
		{
			entity.AcceptChanges();
			return InsertOrUpdate(
				entity.PortletID, 
				entity.Name, 
				entity.Description, 
				entity.Touched, 
				entity.ModuleID
				);
		}
		
		#endregion
		
		#region Delete
		
		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static bool Delete (Portlet entity)
		{
			entity.AcceptChanges();
			return Delete(
				entity.PortletID
			);
		}

		[DataObjectMethod(DataObjectMethodType.Delete, true)]
		public static bool Delete (int portletID)
		{
			using(SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["ManagedFusion"].ConnectionString))
			{
				using (SqlCommand command = connection.CreateCommand())
				{
					command.CommandText = "ManagedFusion_Portlet_Delete";
					command.CommandType = CommandType.StoredProcedure;
					
					command.Parameters.AddWithValue("@PortletID", portletID);
					
					bool success = false;
					
					try
					{
						connection.Open();
						command.ExecuteNonQuery();
					
						success = true;
					} catch (Exception exc) {
						Debug.WriteLine(exc);
						
						success = false;
					} finally {
						connection.Close();
					}
					
					return success;
				}
			}
		}
		
		#endregion

		#endregion
		
		#region Column Variables
		
		#region Primary key(s)
		
		/// <summary>			
		/// Column PortletID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Portlet"</remarks>
		private int _portletID = 0;

		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// Column Name : 
		/// </summary>
		private string _name = String.Empty;

		/// <summary>
		/// Column Description : 
		/// </summary>
		private string _description = (string)null;

		/// <summary>
		/// Column Touched : 
		/// </summary>
		private DateTime _touched = (DateTime)SqlDateTime.MinValue;

		/// <summary>
		/// Column ModuleID : 
		/// </summary>
		private Guid _moduleID = Guid.Empty;

		#endregion
		
		#endregion
		
		#region Constructor
		
		///<summary>
		/// Creates a new <see cref="Portlet"/> instance.
		///</summary>
		///<param name="PortletID"></param>
		///<param name="Name"></param>
		///<param name="Description"></param>
		///<param name="Touched"></param>
		///<param name="ModuleID"></param>
		public Portlet (string name, string description, DateTime touched, Guid moduleID)
		{
			this._isMarkedForDeletion = false;
			this._isDirty = true;
			this._isNew = true;
			this._autoUpdate = true;
				
			this._name = name;
			this._description = description;
			this._touched = touched;
			this._moduleID = moduleID;
		}
		
		public Portlet ()
		{
			this._isMarkedForDeletion = false;
			this._isDirty = false;
			this._isNew = true;
			this._autoUpdate = true;
		}
		
		#endregion
		
		#region Properties
		
		#region Foreign Keys
		
		[Browsable(false)]
		public ContainerPortletLinkCollection ContainerPortletLinksWithPortletIDForPortletID
		{
			get 
			{
				return ContainerPortletLink.GetList("PortletID = " + _portletID + "");
			}
		}
		
		[Browsable(false)]
		public PortletPropertyCollection PortletPropertysWithPortletIDForPortletID
		{
			get 
			{
				return PortletProperty.GetList("PortletID = " + _portletID + "");
			}
		}
		
		[Browsable(false)]
		public PortletRoleCollection PortletRolesWithPortletIDForPortletID
		{
			get 
			{
				return PortletRole.GetList("PortletID = " + _portletID + "");
			}
		}
		
		#endregion
		
		/// <summary>Gets the PortletID value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is int</value>
		[ReadOnly(true)]
		[Description("")]
		[DataObjectField(true, true, false, 4)]
		public int PortletID
		{
			get { return this._portletID; }
		}
		
		/// <summary>Gets or sets the Name value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is nvarchar</value>
		[Description("")]
		[DataObjectField(false, false, false, 32)]
		public string Name
		{
			get { return this._name; }
			set
			{
				if (_name == value)
					return;
					
				_name = value;
				this._isDirty = true;
				
				// if auto update is turned on update this
				if (AllowAutoUpdate) Update(this);
			}
		}
		
		/// <summary>Gets or sets the Description value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is nvarchar</value>
		[Description("")]
		[DataObjectField(false, false, true, 128)]
		public string Description
		{
			get { return this._description; }
			set
			{
				if (_description == value)
					return;
					
				_description = value;
				this._isDirty = true;
				
				// if auto update is turned on update this
				if (AllowAutoUpdate) Update(this);
			}
		}
		
		/// <summary>Gets or sets the Touched value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is datetime</value>
		[Description("")]
		[DataObjectField(false, false, false, 8)]
		public DateTime Touched
		{
			get { return this._touched; }
			set
			{
				if (_touched == value)
					return;
					
				_touched = value;
				this._isDirty = true;
				
				// if auto update is turned on update this
				if (AllowAutoUpdate) Update(this);
			}
		}
		
		/// <summary>Gets or sets the ModuleID value for the column.</summary>
		/// <remarks></remarks>
		/// <value>This type is uniqueidentifier</value>
		[Description("")]
		[DataObjectField(false, false, false, 16)]
		public Guid ModuleID
		{
			get { return this._moduleID; }
			set
			{
				if (_moduleID == value)
					return;
					
				_moduleID = value;
				this._isDirty = true;
				
				// if auto update is turned on update this
				if (AllowAutoUpdate) Update(this);
			}
		}
		

		private bool _autoUpdate = true;
		/// <summary>True if the entity should commit changes as soon as they are made.</summary>
		[Browsable(false)]
		public bool AutoUpdate
		{
			get { return this._autoUpdate; }
			set { _autoUpdate = value; }
		}

		private bool _isMarkedForDeletion = false;
		/// <summary>Gets if the object has been <see cref="MarkToDelete"/>.</summary>
		[Browsable(false)]
		public bool IsMarkedForDeletion
		{
			get { return this._isMarkedForDeletion; }
		}

		private bool _isDirty = false;
		/// <summary>Indicates if the object has been modified from its original state.</summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[Browsable(false)]
		public bool IsDirty
		{
			get { return this._isDirty; }
		}

		private bool _isNew = false;
		/// <summary>Indicates if the object is new.</summary>
		///<value>True if objectis new; otherwise False;</value>
		[Browsable(false)]
		public bool IsNew
		{
			get { return this._isNew; }
		}

		/// <summary>Gets a value indicating if AutoUpdate is allowed on this entity.</summary>
		private bool AllowAutoUpdate 
		{
			get { return (!IsNew && !IsMarkedForDeletion) && AutoUpdate; }
		}

		#endregion
		
		#region Methods
		
		internal void Merge (Portlet entity)
		{
			this._portletID = entity._portletID;
			this._name = entity._name;
			this._description = entity._description;
			this._touched = entity._touched;
			this._moduleID = entity._moduleID;
		}

		/// <summary>Begin the update process.</summary>
		public void BeginUpdate()
		{
			this.AutoUpdate = false;
		}
		
		/// <summary>End the update process and commit changes.</summary>
		public void EndUpdate()
		{
			this.EndUpdate(true);
		}
		
		/// <summary>End the update process</summary>
		public void EndUpdate(bool commit)
		{
			this.AutoUpdate = true;
			
			if (commit)
				this.CommitChanges();
		}
		
		/// <summary>Accepts the changes made to this object by setting each flags to false.</summary>
		internal void AcceptChanges()
		{
			this._isMarkedForDeletion = false;
			this._isDirty = false;
			this._isNew = false;
		}
		
		///<summary>Currently not supported.</summary>
		public void CancelChanges()
		{
			throw new NotSupportedException("Cancel changes is not currently supported.");
		}
		
		///<summary>Delete this entity.</summary>
		public void Delete()
		{
			this._isMarkedForDeletion = true;
			
			if (!IsNew && AutoUpdate) Delete(this);
		}
		
		#endregion
		
		#region ITable<int> Members

		[DataObjectField(true, true, false)]
		int ITable<int>.PrimaryKey
		{
			get { return _portletID; }
		}

		/// <summary>Commit the changes to the database.</summary>
		public void CommitChanges()
		{
			if (this.IsNew)
				Insert(this);
			
			else if (this.IsMarkedForDeletion)
				Delete(this);
				
			else if (this.IsDirty)
				Update(this);
		}

		#endregion
	}
	
	#region Portlet Columns
	
	public enum PortletColumn
	{
		/// <summary></summary>
		PortletID,
 
		/// <summary></summary>
		Name,
 
		/// <summary></summary>
		Description,
 
		/// <summary></summary>
		Touched,
 
		/// <summary></summary>
		ModuleID 
	}
	
	#endregion
	
	#region Portlet Collection
	
	public class PortletCollection : TableCollection<int, Portlet>
	{
	}
	
	#endregion
}